version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --log=true --accesslog=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  whoami-1:
    image: traefik/whoami:latest
    ports:
      # The HTTP port
      - "80"
    labels:
      - "traefik.http.routers.whoami-1.rule=Host(`works.middenii.com`) && PathPrefix(`/whoami-1`)"

  # whoami-2:
  #   image: traefik/whoami:latest
  #   ports:
  #     # The HTTP port
  #     - "80"
  #   labels:
  #     - "traefik.http.routers.whoami-2.rule=Host(`works.middenii.com`) && PathPrefix(`/whoami-2`)"
